In [7]:
import numpy as np

In [8]:
#Importe de siniestros anuales por poliza.
siniestros = np.array([450,800,1200,1500,2300,5000])
exposiciones = np.array([1,1,1,0.5,2,1])
pesos = np.array([0.1,0.15,0.2,0.1,0.25,0.2])

Funciones estadisticas de numpy:

np.mean()
np.median()
np.sum()
np.std()
np.var()
np.percentil()
np.quantile()

In [9]:
print(np.mean(siniestros))
print(np.median(siniestros))
print(np.sum(siniestros))
print(np.std(siniestros))
print(np.var(siniestros))
print(np.percentile(siniestros,95))
print(np.quantile(siniestros,0.5))

1875.0
1350.0
11250
1512.6549507405844
2288125.0
4325.0
1350.0


Segmentacion de riesgos: Clasificacion automatica de mi riesgo en funcion de mi prima:
 np.where()

In [10]:
riesgo = np.where(siniestros>2000,"Alto","Normal")
print(riesgo)

['Normal' 'Normal' 'Normal' 'Normal' 'Alto' 'Alto']


np.clip() -> Creamos una prima con limite de cobertura

In [11]:
pago_limitado =np.clip(siniestros,0,3000)
print(pago_limitado)

[ 450  800 1200 1500 2300 3000]


np.maximun() -> deducir x euros de la poliza

In [12]:
pago_deducido=np.maximum(siniestros -500,0)
print(pago_deducido)

[   0  300  700 1000 1800 4500]


Media ponderada np.dot(data, ponderacion)

In [15]:
print(np.dot(siniestros,pesos))

2130.0


pagos acumulados - Evolucion acumulado del coste
    np.cumsum(vector)

In [16]:
print(np.cumsum(siniestros))

[  450  1250  2450  3950  6250 11250]


Frecuencia de siniestros- funcion de poisson

In [17]:
print(np.random.poisson(0.8,10)) # poisson(lambda,tamaño de la muestra)

[3 0 0 0 2 0 0 2 1 0]


np.power() - Ej: calcular valor presente a dos años con un 3% anual

In [18]:
VA=siniestros/np.power(1.03,2)
print(VA)

[ 424.16815911  754.07672731 1131.11509096 1413.8938637  2167.97059101
 4712.97954567]


Evolucion de la siniestralidad en el tiempo usando como referencia la cantidad de siniestros
np.polyfit(años,data)

In [19]:
años = np.arange(len(siniestros))
tendencia = np.polyfit(años,siniestros,0)
print(tendencia)

[1875.]


Ranking de riesgos - Identificar las polizas más peligrosas - np.argsort()

In [22]:
rank=np.argsort(siniestros)[::-1]
print(rank)

[5 4 3 2 1 0]
